title: Priyesh Peswani # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A diversely skilled and highly resourceful Infotainment and Telematics Domain Expert with 6 years of experience in Automotive and Infotainment and Telematics domain with functional and cross-functional knowledge of Audio, Camera, Smartphone, VR, Settings and Home features.  
  <br><br>
  A results-oriented enterprise solutions architect with extensive knowledge of AWS cloud offerings. Proficient in Software Engineering, Business Analysis and Technical Solution Design resulting in highly maintainable and scalable digital solutions.
  <br><br>
  <a href="https://www.linkedin.com/in/priyeshpeswani/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
